### ISSUE TITLE
[BUG] System cannot find file when downloading and convert hls Stream

### ISSUE THREAD

**Issue by TrackLab** [wolfswolke/aniworld_scraper#41]
**Describe the bug:**
So, this tool has worked fine all the time. I recently switched to Win11, and now its broken. So I am a little surprised by that. I used the V1.9 release the whole time, because the master branch is a newer one that never got a release. The master branch is broken, with this report. The V1.9 release seems to work fine as of right now. So I am going to continue using that for now. 

```
2024-04-11 10:41:28 - LOADING - src.logic.downloader - Provider VOE - File output/anime/bna/Season 01/bna - s01e01 - Deutsch.mp4 added to queue.
2024-04-11 10:41:28 - INFO - src.start_app - File name will be: output/anime/bna/Season 01/bna - s01e02 - Deutsch.mp4
Exception in thread Thread-1 (download_and_convert_hls_stream):
Traceback (most recent call last):
  File "C:\Users\Cliffford\.conda\envs\AniWorldDownloaderV2\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Cliffford\.conda\envs\AniWorldDownloaderV2\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "Z:\aniworld_scraper-main\src\logic\downloader.py", line 53, in download_and_convert_hls_stream
    subprocess.run(ffmpeg_cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\Cliffford\.conda\envs\AniWorldDownloaderV2\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cliffford\.conda\envs\AniWorldDownloaderV2\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Cliffford\.conda\envs\AniWorldDownloaderV2\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

**Expected behavior:**
To create a .mp4 file. It does create the folders, but not a file.

**Comment by wolfswolke** [comment]
@TrackLab `FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden` That means the FFMPEG exe was not found in your Folder. Did you put it into your workingdir?
Like this: `AniWorldScraper\ffmpeg.exe`

**Comment by TrackLab** [comment]
I had the ffmpeg inside the src folder, like I have in 1.9. Has that changed?
Also, a side question, V 1.9 used whatever source was available VOE, Streamtape, etc.

Now the master branch makes it look like you can only chose one host? Since you set one in the call of main.py, or in the bat file.

**Comment by wolfswolke** [comment]
The current main Branch starts MAIN.py which is in the root folder. Ill add a check that checks if ffmpeg is in the root folder or src and use that.
Also the settings provider is a feature i added. You set the provider you want to use and if that one doesn't work it automatically chooses a different one.

**Comment by wolfswolke** [comment]
@TrackLab i added some logic that checks where the exe is or if it is installed.
You can now run the main.py like the batch does or use the batch.

**Comment by TrackLab** [comment]
Perhabs a note in the console with the link to ffmpeg's download, when it cannot be found is a good idea for new users. Either way, thanks.
