### ISSUE TITLE
[ERROR]  I get Python Exception while trying to download

### ISSUE THREAD

**Issue by KemMuammer** [wolfswolke/aniworld_scraper#51]
I get this when I try to download something. Is this normal can I somehow fix this?

```
Exception in thread Thread-1 (download_and_convert_hls_stream):
Traceback (most recent call last):
  File "C:\Users\kemmuammer\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\kemmuammer\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\kemmuammer\Downloads\aniworld_scraper-main\aniworld_scraper-main\src\logic\downloader.py", line 60, in download_and_convert_hls_stream
    subprocess.run(ffmpeg_cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\kemmuammer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kemmuammer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kemmuammer\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

**Comment by wolfswolke** [comment]
@KemMuammer 
subprocess.run(ffmpeg_cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
Did you download FFMPEG and either installed it or placed the portable version in the folder?

**Comment by KemMuammer** [comment]
![image](https://github.com/wolfswolke/aniworld_scraper/assets/32688950/5dda6845-4af8-4ab2-9fc8-0ea8bb104169)
I did and added to the src folder. Should I rename it to only ffmpeg?

**Comment by wolfswolke** [comment]
no you need the exe or have it installed @KemMuammer 
![image](https://github.com/wolfswolke/aniworld_scraper/assets/34097612/9b75e2d6-e321-4a45-a313-23c03d7eaeff)

**Comment by KemMuammer** [comment]
@wolfswolke Yeah that worked thanks and also I dont know why but the ffmpeg download I have does not come with the exe variant. I dont know why. But that is a different issue.
