### ISSUE TITLE
[BUG] File not found after downloaded started

### ISSUE THREAD

**Issue by TrackLab** [wolfswolke/aniworld_scraper#57]
**Describe the bug:**
Trying to download a series, which fails once the download tries to start.
My guess is that it cannot create the mp4 file, but it has worked before, and suddenly stopped working during download of previous stuff, which worked fine. 

**Logs:**

```
> Starting scraper now...
> ←[1;94m2024-07-18 21:35:20 - INFO - src.start_app - ------------- AnimeSerienScraper v01-10-00 started ------------ ←[0m
> ←[1;94m2024-07-18 21:35:20 - INFO - src.start_app - Season Override detected. Override set to: 10 ←[0m
> ←[1;94m2024-07-18 21:35:21 - INFO - src.start_app - Season 10 has 22 Episodes. ←[0m
> ←[1;94m2024-07-18 21:35:21 - INFO - src.start_app - File name will be: output/serie/the-blacklist_(2013)/Season 10/the-blacklist - s10e01 - Deutsch.mp4 ←[0m
> ←[1;94m2024-07-18 21:35:22 - INFO - src.logic.search_for_links - Found window.location.href. Redirecting... ←[0m
> ←[1;93m2024-07-18 21:35:22 - LOADING - src.logic.downloader - Provider VOE - File output/serie/the-blacklist_(2013)/Season 10/the-blacklist - s10e01 - Deutsch.mp4 added to queue. ←[0m
> ←[1;94m2024-07-18 21:35:22 - INFO - src.start_app - File name will be: output/serie/the-blacklist_(2013)/Season 10/the-blacklist - s10e02 - Deutsch.mp4 ←[0m
> Exception in thread Thread-1 (download_and_convert_hls_stream):
> Traceback (most recent call last):
>   File "C:\Program Files\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
>     self.run()
>   File "C:\Program Files\Python312\Lib\threading.py", line 1010, in run
>     self._target(*self._args, **self._kwargs)
>   File "Z:\aniworld_scraper-V-2.04\src\logic\downloader.py", line 60, in download_and_convert_hls_stream
>     subprocess.run(ffmpeg_cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>   File "C:\Program Files\Python312\Lib\subprocess.py", line 548, in run
>     with Popen(*popenargs, **kwargs) as process:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\Python312\Lib\subprocess.py", line 1026, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Program Files\Python312\Lib\subprocess.py", line 1538, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
```

Using 2.04, btw.

**Comment by speedyconzales** [comment]
make sure that `ffmpeg -version` does work for you in the terminal. If not then this is the problem. Make sure `ffmpeg` is in the PATH

**Comment by TrackLab** [comment]
Christ youre right. I forgot about ffmpeg, AGAIN.
I suggest some error handling, a simple check if FFMPEG is available. Gonna make a feature request for that, and in the meantime try to see if I can add it myself
