### ISSUE TITLE
[BUG]  manuel downloader FileNotFoundError

### ISSUE THREAD

**Issue by LuciDuki** [wolfswolke/aniworld_scraper#9]
Hi, the manuel downloader isn't working for me.

here is the output I get:

`2023-03-09 10:25:17,773: INFO    downloader.py -> File output/S15-E52-one-piece.mp4 added to queue.
Exception in thread Thread-2 (download):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gaming\Desktop\aniworld_scraper\src\logic\downloader.py", line 17, in download
    with open(file_name, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/S15-E52-one-piece.mp4'`

Maybe you can give me hint whats wrong

thx in advance

**Comment by wolfswolke** [comment]
@LuciDuki Please set Line 23 to debug.
From: setup_logging("info")
To: setup_logging("debug")
After that send me the Logging output.
And a fyi the Microsoft Store Version of Python has alot of issued from what i have seen and got as bug reports. Just so you know that could be a issue but we will first look at the log.

**Comment by LuciDuki** [comment]
Hi, debug is enabled:

`2023-03-09 13:16:01,354: DEBUG   We have Read Permission
2023-03-09 13:16:01,354: DEBUG   We have Write Permission
2023-03-09 13:16:01,701: DEBUG   manuel_episode_download.py -> Link to redirect is: https://aniworld.to/redirect/591100
2023-03-09 13:16:47,283: DEBUG   manuel_episode_download.py -> Return is: https://vidoza.net/embed-2uqviwbrd5ea.html
2023-03-09 13:16:47,284: DEBUG   search_for_links ->Enterd Vidoza to cache
2023-03-09 13:16:47,516: DEBUG   search_for_links ->Exiting Vidoza to Cache
2023-03-09 13:16:47,516: DEBUG   manuel_episode_download.py -> Vidoza Cache URL is: https://str26.vidoza.net/nvl4fa2g7ueuieno3wqq3gh2hekgjmylst2nijbqcea67x4humbdtfwlmdra/v.mp4
2023-03-09 13:16:47,517: DEBUG   downloader.py -> Entered Downloader.
2023-03-09 13:16:47,518: DEBUG   downloader.py -> Entered download with these vars: Link: https://str26.vidoza.net/nvl4fa2g7ueuieno3wqq3gh2hekgjmylst2nijbqcea67x4humbdtfwlmdra/v.mp4, File_Name: output/S15-E52-one-piece.mp4
2023-03-09 13:16:47,518: INFO    downloader.py -> File output/S15-E52-one-piece.mp4 added to queue.
Exception in thread Thread-2 (download):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gaming\Desktop\aniworld_scraper\src\logic\downloader.py", line 17, in download
    with open(file_name, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/S15-E52-one-piece.mp4'`

Python 3 is actually installed, also the store version as it seems. After work i will change it to the correct python and try again ^^

thx

**Comment by wolfswolke** [comment]
@LuciDuki pull the image again. Forgot to add the mkdir. (Manuel is not used often so i didnt check.

**Comment by wolfswolke** [comment]
fixed
